from random import randrange
name=input("name:")
studentsList = ["SARETH","SEAVY","RATHTEKA","SREYHON","VANTHORN","SOK","TOUN","SREYTOUCH","CHAINY","SOM",
"SIMENG","NHORK","SREYNOT","THIN","SEANGHAY","LYHUOY","SOPHANNA","NIMOUT","VOULEAK","CHET",
"SINY","SOTHEAN","SOPHORN","SREYHIEB","MENGHOUR","NISAI","CHANTHEA","PHEARAK","SOMOUN","SREYNICH",
"SAOLEE","RIN","ON","SOPHANNA","CHANTHY","MOLIKA","BUNSAL","SOKTHANG","DYNA","SARA",
"VOUCHLY","SOTHOUN","LYDEN","MONYRA","VUN","LANH","PHALLY","SREYPICH","SENGHIM","DAVY","CHUM","LYHEANG","KOEMSAK","VICHEKA","LAMYAI","CHANTHOU","KUNTHY","SOPHEA","VANTHEAV","SOPHEAK","NARATH","SREYNGIT","MENGHEANG","VUTHY","CHANRY","CHANNARY","LYHOR","THALY","HOUTCHHAY","SOMPHORS","SINET","SREY AEM","THON","PROS"]
index=randrange(0,74)
print(studentsList[index])